### ISSUE TITLE
The message has been displayed on the screen after clicking on the "Nickname" field in Profile tab

### ISSUE THREAD

**Issue by m-tetiana** [dataengi/crm-seed-ui#5]
#### expected behavior
The message is not displayed on the screen after clicking the mouse into "Nickname" field. 

#### actual behavior
The message "Nickname is not valid" has been displayed on the screen.

#### precondition
New Company is created and users are added to it.
User is registered and login to the application as Company manager.

#### steps to reproduce
1. Go to Profile tab (right corner).
2. Click in the field "Nickname".
3. Click the mouse on the free space on the screen.

**Comment by OleksivO** [comment]
Check please, because I can't reproduce it

**Comment by m-tetiana** [comment]
Login to app as Company manager of your test Company
