### ISSUE TITLE
On the left corner near "Contacts" title in brackets, the nickname of the user is not displayed

### ISSUE THREAD

**Issue by m-tetiana** [dataengi/crm-seed-ui#8]
#### expected behavior
On the left corner near "Contacts" title in brackets should display the nickname of the user. 

#### actual behavior
On the left corner near "Contacts" title in brackets, the nickname of the user is not displayed.

#### precondition
A user should be login with Company manager or Manager role.
Other users which are related to the company are registered and have created contacts.

#### steps to reproduce
1. Go to Admin tab.
2. Go to Users subtab.
3. Click on "Contacts" button near a necessary user.

**Comment by OleksivO** [comment]
Explain better please, can't reproduce

**Comment by m-tetiana** [comment]
To reproduce this bug, first of all, you should create your company and invite users to it. Than, create some contacts for your users. After all login as Company manager or Manager to app and go to Admin tab -> Users subtab -> in list of users choose one -> click on Contacts button, so than you'll be redirected into page with list of contacts of user that you selected from a list. 
See attachment.
![screenshot from 2017-12-14 17-17-17](https://user-images.githubusercontent.com/26620393/33999326-dceb4936-e0f2-11e7-8432-7cfbf05f2252.png)
